# Site settings
title: Keyduq
description: 'Full stack developer, javascript lover, also php and java (Android) developer'
url: 'http://keyduq.github.io/'
baseurl: '/'
google_analytics: 'UA-85921314-1'
disqus_shortname: 'keyduq'

author:
  name: 'Keyvin Duque'
  email: thkeyduq@gmail.com
  twitter_username: keyduq
  facebook_username: keyduq
  github_username:  keyduq
  linkedin_username:  keyduq

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
